name: ci
on:
  workflow_dispatch:
  push:
  pull_request:

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Nix
        uses: cachix/install-nix-action@v17
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Configure binary cache
        uses: cachix/cachix-action@v12
        with:
          name: nixos-vfio
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Flake check
        run: nix flake check